sudo: false
dist: xenial
language: c
before_script: .travis-scripts/install-poly.sh

env:
  global:
    - PATH=$PATH:$HOME/bin LD_LIBRARY_PATH=$HOME/lib SML=poly BUILDOPTS=

script: .travis-scripts/acquire-hol.sh && HOL/bin/Holmake

