sudo: false
dist: xenial
language: c

branches:
  only:
  - master
  - /^\d+\.\d+\.\d+-release$/

env:
  global:
    - PATH=$PATH:$HOME/bin LD_LIBRARY_PATH=$HOME/lib SML=poly BUILDOPTS=

addons:
  apt:
    packages:
    - python3
    - python3-pip

before_install:
- pip3 install --user --upgrade setuptools
- pip3 install --user GitPython github3.py

before_script: .travis-scripts/install-poly.sh && .travis-scripts/acquire-hol.sh

script: travis_wait HOL/bin/Holmake

deploy:
  # Deploy tagged releases
  - provider: releases
    api-key: $GH_TOKEN
    skip_cleanup: true
    file:
      - splat
      - $HOME/lib/libpolyml.so.10
    on:
      tags: true
  # Deploy continuous integration build
  - provider: releases
    api-key: $GH_TOKEN
    name: Continuous Integration Build
    body: Automated CI/CD build via Travis-CI
    prerelease: true
    overwrite: true
    skip_cleanup: true
    target_commitish: $TRAVIS_COMMIT
    file:
      - splat
      - $HOME/lib/libpolyml.so.10
    on:
      branch: master
  # Clean up stale continuous integration builds
  - provider: script
    script: python3 .travis-scripts/manage_builds.py "Continuous Integration Build"
    on:
      branch: master

